version: '3.8'

services:
  steam_games_postgres:
    image: postgres:16.0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: steam_games
