version: '3.8'

services:
  steam_users_postgres:
    image: postgres:16.0
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: steam_users
